[
  {
    "Id": "730986",
    "ThreadId": "287468",
    "Html": "\r\n<p>I get this inner exception when I make changes on the graph, here is the stack trace:&nbsp;</p>\r\n<p>at System.Collections.Generic.Dictionary`2.get_Item(TKey key)&nbsp; &nbsp;</p>\r\n<p>at QuickGraph.BidirectionalGraph`2.ContainsEdge(TEdge edge)&nbsp;</p>\r\n<p>at GraphSharp.Controls.GraphLayout`3.HighlightTriggerEventHandler(Object sender, HighlightTriggeredEventArgs args)</p>\r\n<p>How can I get passed this problem?</p>\r\n",
    "PostedDate": "2012-01-26T02:14:57.543-08:00",
    "UserRole": null,
    "MarkedAsAnswerDate": null
  },
  {
    "Id": "731095",
    "ThreadId": "287468",
    "Html": "<p>I had this message when i tried to remove a not existing vertex or edge in my graph.</p>\n<p>When did this message appear?</p>",
    "PostedDate": "2012-01-26T07:24:57.653-08:00",
    "UserRole": null,
    "MarkedAsAnswerDate": null
  },
  {
    "Id": "732171",
    "ThreadId": "287468",
    "Html": "<p>I get this message a while after removing the existing graph and displaying the new graph, not while removing... any idea?</p>",
    "PostedDate": "2012-01-28T23:56:46.95-08:00",
    "UserRole": null,
    "MarkedAsAnswerDate": null
  },
  {
    "Id": "732221",
    "ThreadId": "287468",
    "Html": "<p>I solved it, all i had to do is:</p>\r\n<pre>graphLayout.Children.Clear();\r\n</pre>\r\n<p>before I do changes on the graph</p>\r\n<p>&nbsp;</p>",
    "PostedDate": "2012-01-29T04:17:01.873-08:00",
    "UserRole": null,
    "MarkedAsAnswerDate": null
  }
]